FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

EXPOSE 80
WORKDIR /app

COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./src /app

ENTRYPOINT ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]
